name: CI

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"
  repository_dispatch:
    types: [ run_build ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      # originally taken from https://dev.to/frangarcj/handyvita-compiling-ps-vita-homebrew-with-github-actions-3k9, but it used a lot of outdated actions
      - uses: actions/checkout@v6
      - name: prep for artifacts
        run: apk add nodejs
      - name: setup non-root for libpng
        run: |
          adduser nonroot -D -H
          apk add doas
          echo permit nopass keepenv setenv { PATH } root as nonroot > /etc/doas.d/doas.conf
          echo $PATH
          ls -la /usr/local/vitasdk/bin
      - name: build libpng
        run: |
          chmod 777 libpng -R
          cd libpng
          doas -u nonroot env
          doas -u nonroot vita-makepkg
          vdpm libpng-1.6.29-1-arm.tar.xz
      - name: cmake
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Compile project
        run: |
          cd build
          make
      - name: Archive build artifacts
        if: ${{ !env.ACT }} # broken, https://github.com/nektos/act/issues/6022
        uses: actions/upload-artifact@v7
        with:
          path: build/pngshot-ssu.suprx
      - name: version variable
        run: |
          export APP_VER=$(cat version.txt)
      - name: Draft Release
        uses: softprops/action-gh-release@v3
        if: ${{github.ref == 'refs/heads/master' && !env.ACT}}
        with:
          draft: true
          tag_name: "${{ env.APP_VER }}"
          files: build/pngshot-ssu.suprx

# https://github.com/OctoNezd/VNDS-LOVE-TOUCH/blob/main/.github/workflows/main.yml
