name: CI

on:
  push:
    paths-ignore:
      - "*.md"
  repository_dispatch:
    types: [ run_build ]

permissions:
  artifact-metadata: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      # originally taken from https://dev.to/frangarcj/handyvita-compiling-ps-vita-homebrew-with-github-actions-3k9, but it used a lot of outdated actions
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: prep for artifacts
        run: apk add nodejs github-cli
      - name: setup non-root for libpng
        run: |
          adduser nonroot -D -H
          apk add doas
          echo permit nopass keepenv setenv { PATH } root as nonroot > /etc/doas.d/doas.conf
          echo $PATH
          ls -la /usr/local/vitasdk/bin
      - name: Cache libpng
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        id: cache-lpng
        with:
          path: libpng/libpng-1.6.29-1-arm.tar.xz
          key: "libpng-${{ hashFiles('libpng/VITABUILD') }}"
      - name: build libpng
        if: ${{ steps.cache-lpng.outputs.cache-hit != 'true' }}
        run: |
          chmod 777 libpng -R
          cd libpng
          doas -u nonroot env
          doas -u nonroot vita-makepkg
      - name: install libpng
        run: |
          cd libpng
          vdpm libpng-1.6.29-1-arm.tar.xz
      - name: cmake
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Compile project
        run: |
          cd build
          make
      - name: Archive build artifacts
        if: ${{ !env.ACT }} # broken, https://github.com/nektos/act/issues/6022
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          path: build/pngshot-ssu.suprx
      - name: version variable
        run: |
          export APP_VER=$(cat version.txt)
      - name: Draft Release
        if: ${{github.ref == 'refs/heads/master' && !env.ACT}}
        run: |
          gh release create -d -t ${{ env.APP_VER }} ${{ env.APP_VER }} build/pngshot-ssu.suprx
        env:
          GH_TOKEN: ${{ github.token }}
